import Head from 'next/head'
import { Header, Navbar, Projects, Technologies } from '../components/index'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Header />
      <Projects />
      <Technologies />
    </div >
  )
}
